name: Sphinx Make HTML
run-name: ${{ github.actor }} is building the HTML
on: push
jobs:
  Install-Compile-Commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Prepare Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
          
      - name: Install Sphinx and Packages
        run: |
          pip install sphinx
          pip install piccolo_theme
      - name: Build HTML
        run: make html
            
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add -A
          git commit -am "Automatic Sphinx build on $(date)"
          git push -f origin main
